repos:
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.40.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: pytest -vvxs --cov -s
        language: system
        pass_filenames: false
        always_run: true
