service: system-notifications1

package:
  individually: true

provider:
  name: aws
  runtime: python3.8
  region: sa-east-1
  memorySize: 128
  stage: ${opt:stage, "staging"}

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    layer:
      name: notifications-layer
      description: Notifications Service
      compatibleRuntimes:
        - python3.8

functions:
  app:
    package:
      include:
        - "app.py"
      exclude:
        - "package.json"
        - "package-lock.json"
        - ".serverless/**"
        - ".virtualenv/**"
        - "node_modules/**"

    handler: app.handler
    environment:
      STAGE: ${self:provider.stage}
      ENVIRON_TYPE: staging
      STAGING__SLACK_API_TOKEN: ${env:STAGING__SLACK_API_TOKEN}
      STAGING__SECRET: ${env:STAGING__SECRET}
    layers:
      - { Ref: PythonRequirementsLambdaLayer }
    events:
      - http:
          method: any
          path: /{proxy+}
